// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqewmrfzywumeiqoppuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZXdtcmZ6eXd1bWVpcW9wcHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjc1NTAsImV4cCI6MjA2NTg0MzU1MH0.6WHXTlbhN5ZrpTZBpLiy3XBbg1KdtD85-P0y8w4AeDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);